Adding an additional test to try get to the bottom of the occasionally failing test
```
Regression

oauth-service.should create tokens atomically (from Mocha Tests)

Failing for the past 1 build (Since Failed#3784 )
Took 24 ms.
add description
Error Message

&quot;4ee8deeb3e53bd15c3e1066a98bf9463083c926e&quot; == &quot;0ac12d24938f8ce0ee3361a705acc18c21fc89ef&quot;
Stacktrace

AssertionError: &quot;4ee8deeb3e53bd15c3e1066a98bf9463083c926e&quot; == &quot;0ac12d24938f8ce0ee3361a705acc18c21fc89ef&quot;
    at test/integration/services/oauth-service-test.js:47:16
From previous event:
    at Context.&lt;anonymous&gt; (test/integration/services/oauth-service-test.js:42:8)
```