Fix emoji transform to Matrix
Fix https://gitlab.com/gitterHQ/webapp/-/issues/2641

Follow-up from https://gitlab.com/gitterHQ/webapp/-/merge_requests/2077 which throws an error when we try to deploy in production because emojify is not available.

We ignore the `public/repo/` directory in our [build-scripts](https://gitlab.com/gitterHQ/webapp/-/blob/b500176c32221b9afed16d8611e3adbd7a2ace2a/build-scripts/gulpfile-clientapp.js#L23) which holds `emojify` so it's not available on disk. For the frontend, it's already bundled in by webpack.

```
2020-12-01T00:52:53.583Z - info: Starting server/web.js
Dec 01 00:52:54 webapp-04 ns[6501]: 2020-12-01T00:52:54.299Z - error: ----------------------------------------------------------------
Dec 01 00:52:54 webapp-04 ns[6501]: 2020-12-01T00:52:54.300Z - error: -- A VeryBadThing has happened.
Dec 01 00:52:54 webapp-04 ns[6501]: 2020-12-01T00:52:54.300Z - error: ----------------------------------------------------------------
Dec 01 00:52:54 webapp-04 ns[6501]: 2020-12-01T00:52:54.300Z - error: Uncaught exceptionError: Cannot find module '../../../public/repo/emojify/emojify' message=Cannot find module '../../../pub
Dec 01 00:52:54 webapp-04 ns[6501]: 2020-12-01T00:52:54.300Z - error: Error: Cannot find module '../../../public/repo/emojify/emojify'
```