Add docs for how to solve the missing cld dep problem
When someone runs into `Error: Cannot find module './build/Release/cld'`
add a follow-up step to solve the situation. I'm not sure how this situation
can occur since you run `npm install` and it should install it.

This was spawned from @jeanduplessis running into the same error, https://gitlab.slack.com/archives/C3W3PSR88/p1588061890030700?thread_ts=1588061861.030400&cid=C3W3PSR88

But I have also seen this in the past with some other contributors.