Fix No query solutions error caused by schema clone not getting indexes (chatmessage -> chatmessagebackup)
See https://jira.mongodb.org/browse/SERVER-14643

```
npm run mocha -- C:\Users\MLM\Documents\GitLab\webapp\modules\chats\test\chat-service-test.js --grep "removeAllMessagesForUserId"

MongoError: error processing query: ns=gitter.chatmessagebackupsTree: fromUserId == ObjectId('5c0ea5cca1f239041ca69075')
Sort: {}
Proj: {}
 No query solutions
```

Before:

```
db.chatmessagebackups.getIndexes()
[
        {
                "v" : 1,
                "key" : {
                        "_id" : 1
                },
                "name" : "_id_",
                "ns" : "gitter.chatmessagebackups"
        }
]
```

After:

```
db.chatmessagebackups.getIndexes()
[
        {
                "v" : 1,
                "key" : {
                        "_id" : 1
                },
                "name" : "_id_",
                "ns" : "gitter.chatmessagebackups"
        },
        {
                "v" : 1,
                "key" : {
                        "toTroupeId" : 1,
                        "sent" : -1
                },
                "name" : "toTroupeId_1_sent_-1",
                "ns" : "gitter.chatmessagebackups",
                "background" : true
        },
        {
                "v" : 1,
                "key" : {
                        "fromUserId" : 1
                },
                "name" : "fromUserId_1",
                "ns" : "gitter.chatmessagebackups",
                "background" : true
        }
]
```

```
$ mongo --version
MongoDB shell version v4.0.3

mongo localhost:27017
> db.version()
3.2.14
```