Fix new messages not appearing in chat list (ObjectID serialization)
 - Update faye/bayeux-cluster logging to actually log fatal errors and report errors
 - Adds `npm start -- --inspect-node` so you debug with familiar browser devtools and step through the code
 - Update `@gitterhq/env@0.34.0` for https://gitlab.com/gitlab-org/gitter/env/merge_requests/10
 - Update `@gitterhq/faye@1.1.0-j`(from `gitter-faye`) for https://gitlab.com/gitlab-org/gitter/faye/merge_requests/1

These errors were being hidden away because we didn't have proper logging setup

```
Error: invalid ObjectId, ObjectId.id must be either a string or a Buffer, but is [{"type":"Buffer","data":[]}]
	at ObjectID.toHexString (gitlab\webapp\node_modules\mongoose\node_modules\bson\lib\bson\objectid.js:73:11)
	at ObjectID.toJSON (gitlab\webapp\node_modules\mongoose\node_modules\bson\lib\bson\objectid.js:174:15)
	at Object.stringify (native)
	at Object.publish (gitlab\webapp\node_modules\@gitterhq\faye-redis\faye-redis.js:270:28)
	at Object.publish (gitlab\webapp\node_modules\gitter-faye\javascript\engines\proxy.js:108:25)
	at Object._handle (gitlab\webapp\node_modules\gitter-faye\javascript\protocol\server.js:109:30)
	at Object.<anonymous> (gitlab\webapp\node_modules\gitter-faye\javascript\protocol\server.js:78:14)
	at pipe (gitlab\webapp\node_modules\gitter-faye\javascript\protocol\extensible.js:33:39)
	at pipe (gitlab\webapp\node_modules\gitter-faye\javascript\protocol\extensible.js:36:23)
	at pipe (gitlab\webapp\node_modules\gitter-faye\javascript\protocol\extensible.js:36:23)
	at Object.extension.incoming (gitlab/webapp/server/web/bayeux/extension.js:66:16)
	at pipe (gitlab\webapp\node_modules\gitter-faye\javascript\protocol\extensible.js:38:43)
	at Object.extension.incoming (gitlab/webapp/server/web/bayeux/extension.js:66:16)
	at pipe (gitlab\webapp\node_modules\gitter-faye\javascript\protocol\extensible.js:38:43)
	at Object.extension.incoming (gitlab/webapp/server/web/bayeux/extension.js:66:16)
	at pipe (gitlab\webapp\node_modules\gitter-faye\javascript\protocol\extensible.js:38:43)
	at Object.extension.incoming (gitlab/webapp/server/web/bayeux/extension.js:70:16)
	at pipe (gitlab\webapp\node_modules\gitter-faye\javascript\protocol\extensible.js:38:43)
	at Object.incoming (gitlab/webapp/server/web/bayeux/logging.js:45:5)
	at pipe (gitlab\webapp\node_modules\gitter-faye\javascript\protocol\extensible.js:38:43)
	at Object.pipeThroughExtensions (gitlab\webapp\node_modules\gitter-faye\javascript\protocol\extensible.js:41:5)
	at Object.process (gitlab\webapp\node_modules\gitter-faye\javascript\protocol\server.js:77:12)
	at Object.request (gitlab\webapp\node_modules\gitter-faye\javascript\transport\node_local.js:13:19)
	at Object.sendMessage (gitlab\webapp\node_modules\gitter-faye\javascript\transport\transport.js:41:60)
	at Object._sendEnvelope (gitlab\webapp\node_modules\gitter-faye\javascript\protocol\dispatcher.js:128:40)
	at Object.sendMessage (gitlab\webapp\node_modules\gitter-faye\javascript\protocol\dispatcher.js:106:10)
	at Object.<anonymous> (gitlab\webapp\node_modules\gitter-faye\javascript\protocol\client.js:341:24)
	at pipe (gitlab\webapp\node_modules\gitter-faye\javascript\protocol\extensible.js:33:39)
	at Object.outgoing (gitlab/webapp/server/web/bayeux/super-client.js:12:5)
	at pipe (gitlab\webapp\node_modules\gitter-faye\javascript\protocol\extensible.js:39:43)
	at Object.pipeThroughExtensions (gitlab\webapp\node_modules\gitter-faye\javascript\protocol\extensible.js:41:5)
	at Object._sendMessage (gitlab\webapp\node_modules\gitter-faye\javascript\protocol\client.js:334:10)
	at Object.<anonymous> (gitlab\webapp\node_modules\gitter-faye\javascript\protocol\client.js:299:12)
	at gitlab\webapp\node_modules\gitter-faye\javascript\mixins\deferrable.js:22:49
	at _invoke (gitlab\webapp\node_modules\gitter-faye\javascript\util\promise.js:70:15)
	at Immediate.<anonymous> (gitlab\webapp\node_modules\gitter-faye\javascript\util\promise.js:63:22)
	at runCallback (timers.js:672:20)
	at tryOnImmediate (timers.js:645:5)
	at processImmediate [as _immediateCallback] (timers.js:617:5)
```

```
Error: invalid ObjectId, ObjectId.id must be either a string or a Buffer, but is [{"type":"Buffer","data":[]}]
	at ObjectID.toHexString (C:\\Users\\MLM\\Documents\\GitLab\\webapp\\node_modules\\mongoose\\node_modules\\bson\\lib\\bson\\objectid.js:73:11)
	at ObjectID.toJSON (C:\\Users\\MLM\\Documents\\GitLab\\webapp\\node_modules\\mongoose\\node_modules\\bson\\lib\\bson\\objectid.js:174:15)
	at Object.stringify (native)
	at stringifyInternal (gitlab/webapp/server/web/bayeux/cluster.js:141:21)
	at Object.faye.stringify (gitlab/webapp/server/web/bayeux/cluster.js:157:12)
	at Object.toJSON (gitlab/gitter-faye/javascript/faye.js:130:17)
	at gitlab/gitter-faye/javascript/mixins/logging.js:25:25
	at RegExp.[Symbol.replace] (native)
	at RegExp.[Symbol.replace] (native)
	at String.replace (native)
	at Object.writeLog (gitlab/gitter-faye/javascript/mixins/logging.js:23:32)
	at Object.Faye_Logging.(anonymous function) [as debug] (gitlab/gitter-faye/javascript/mixins/logging.js:50:14)
	at Object.publish (gitlab/gitter-faye-redis/faye-redis.js:268:18)
	at Object.publish (gitlab/gitter-faye/javascript/engines/proxy.js:109:25)
	at Object._handle (gitlab/gitter-faye/javascript/protocol/server.js:109:30)
	at Object.<anonymous> (gitlab/gitter-faye/javascript/protocol/server.js:78:14)
	at pipe (gitlab/gitter-faye/javascript/protocol/extensible.js:32:39)
	at pipe (gitlab/gitter-faye/javascript/protocol/extensible.js:35:23)
	at pipe (gitlab/gitter-faye/javascript/protocol/extensible.js:35:23)
	at Object.extension.incoming (gitlab/webapp/server/web/bayeux/extension.js:66:16)
	at pipe (gitlab/gitter-faye/javascript/protocol/extensible.js:37:27)
	at Object.extension.incoming (gitlab/webapp/server/web/bayeux/extension.js:66:16)
	at pipe (gitlab/gitter-faye/javascript/protocol/extensible.js:37:27)
	at Object.extension.incoming (gitlab/webapp/server/web/bayeux/extension.js:66:16)
	at pipe (gitlab/gitter-faye/javascript/protocol/extensible.js:37:27)
	at Object.extension.incoming (gitlab/webapp/server/web/bayeux/extension.js:70:16)
	at pipe (gitlab/gitter-faye/javascript/protocol/extensible.js:37:27)
	at Object.incoming (gitlab/webapp/server/web/bayeux/logging.js:45:5)
	at pipe (gitlab/gitter-faye/javascript/protocol/extensible.js:37:27)
	at Object.pipeThroughExtensions (gitlab/gitter-faye/javascript/protocol/extensible.js:40:5)
	at Object.process (gitlab/gitter-faye/javascript/protocol/server.js:77:12)
	at Object.request (gitlab/gitter-faye/javascript/transport/node_local.js:13:19)
	at Object.sendMessage (gitlab/gitter-faye/javascript/transport/transport.js:41:60)
	at Object._sendEnvelope (gitlab/gitter-faye/javascript/protocol/dispatcher.js:128:40)
	at Object.sendMessage (gitlab/gitter-faye/javascript/protocol/dispatcher.js:106:10)
	at Object.<anonymous> (gitlab/gitter-faye/javascript/protocol/client.js:331:24)
	at pipe (gitlab/gitter-faye/javascript/protocol/extensible.js:32:39)
	at Object.outgoing (gitlab/webapp/server/web/bayeux/super-client.js:12:5)
	at pipe (gitlab/gitter-faye/javascript/protocol/extensible.js:38:27)
	at Object.pipeThroughExtensions (gitlab/gitter-faye/javascript/protocol/extensible.js:40:5)
	at Object._sendMessage (gitlab/gitter-faye/javascript/protocol/client.js:328:10)
	at Object.<anonymous> (gitlab/gitter-faye/javascript/protocol/client.js:298:12)
	at gitlab/gitter-faye/javascript/mixins/deferrable.js:22:49
	at _invoke (gitlab/gitter-faye/javascript/util/promise.js:70:15)
	at Immediate.<anonymous> (gitlab/gitter-faye/javascript/util/promise.js:63:22)
	at runCallback (timers.js:672:20)
	at tryOnImmediate (timers.js:645:5)
	at processImmediate [as _immediateCallback] (timers.js:617:5)
```