Fix No query solutions error caused by not using an index (notablescan)
See https://jira.mongodb.org/browse/SERVER-14643

```
npm run mocha -- C:\Users\MLM\Documents\GitLab\webapp\test\api-tests\user-orgs-api-tests.js

MongoError: error processing query: ns=gitter.groupsTree: sd.linkPath == "gitter-integration-tests-organisation"
Sort: {}
Proj: {}
 No query solutions
```

```
$ mongo --version
MongoDB shell version v4.0.3

mongo localhost:27017
> db.version()
3.2.14
```