Fix integration settings throwing 500 error
Fix https://gitlab.com/gitlab-org/gitter/webapp/issues/2188

When you visit `https://gitter.im/settings/integrations/<community>/<room>` by using the **Room settings dropdown** -> **Integrations**, the following 500 error is thrown

 - https://sentry.gitlab.net/gitlab/gitter-backend/issues/819726/
 - https://sentry.gitlab.net/gitlab/gitter-backend-staging/issues/820385/

https://gitlab.com/gitlab-org/gitter/webapp/blob/42df77ed40dfa144cd28739bfc44d1846c8206eb/server/handlers/settings.js#L160
```
TypeError: policy.canAdmin(...).then(...).nodeify is not a function
  File "/opt/gitter/gitter-webapp/server/handlers/settings.js", line 160, in adminAccessCheck
    .nodeify(next);
  File "/opt/gitter/gitter-webapp/server/handlers/uri-context/uri-context-resolver-middleware.js", line 34, in null.<anonymous>
    next();
...
(14 additional frame(s) were not displayed)

TypeError: policy.canAdmin(...).then(...).nodeify is not a function
```

![](https://i.imgur.com/l4Yg2ho.png)

This was caused by the change to the policies and policy evaluation from https://dev.gitlab.org/gitlab/gitter/webapp/merge_requests/7 to fix https://gitlab.com/gitlab-org/gitter/webapp/issues/2041
 - Rolled out in [Gitter 19.50.1](https://gitlab.com/gitlab-org/gitter/webapp/blob/develop/CHANGELOG.md#19501-2019-6-25) today(2019-6-25).
 - [First seen](https://sentry.gitlab.net/gitlab/gitter-backend/issues/819726/) when that release went out and the changes in that MR are very relevant to the error

Specifically where we removed the Bluebird promises

 - https://gitlab.com/gitlab-org/gitter/webapp/commit/2533b9a6e7fb27ed09b8e09b3f5f7fe6e99975e3#e651e23431c96ac6fd579df81122e40d524e070c_60_45
 - https://dev.gitlab.org/gitlab/gitter/webapp/commit/c323152611625bb717b9f0b422d92db04e7d9d85?merge_request_iid=7